### GET UXTeam Members
GET http://localhost:4004/tech/UXTeam


### ADD UXTeam Member
POST http://localhost:4004/tech/UXTeam
Content-Type: application/json;IEEE754Compatible=true

{
    "firstName"  : "Milton",
    "lastName" : "Chandradas",
    "age": 25,
    "role": "UX Developer",
    "salary": "9000.00",
    "active": true
}


### Set Active
GET http://localhost:4004/tech/setActive(ID='fa4130a0-2219-42a3-ad5c-f5fa198d0770')

### GET Date
GET http://localhost:4004/tech/getDATE()